### *Jorge Edgardo Viera*


## Módulo 4 · Tarea 4 — NumPy y pandas para análisis de datos


### ***Apartado 1. Trabajando con NumPy***

**NOTA**: Aunque no es solicitado en la consiga, al estar en fase de prueba y desarrollo, utilizo print para mostrar resultados en la consola.

En este codigo ademas de usar las funciones de *NumPy*, usamos cuatro opciones de comparación que son justo las más representativas:

- (==) para ver la comparación detallada elemento a elemento
- (array_equal) como la forma estándar y más directa de saber si dos arrays son idénticos
- (.all()) como alternativa manual al mismo resultado
- (allclose) que es la opción más robusta cuando trabajamos con decimales.

In [1]:
import numpy as np

# Creamos un array con valores del 10 al 100.
array = np.arange(10, 101)

# Ahora invertimos el array.
array_invertido = array[::-1]

# Imprimimos el array original y el invertido.
print("Array original:")
print(array)
print("Array invertido:")
print(array_invertido)

# Creamos un array de dimensión 3x3 con valores del 0 al 8.
array_3x3 = np.arange(9).reshape(3, 3)
print("Array 3x3:")
print(array_3x3)

# Ahora creamos un array identidad de 6x6.
array_identidad = np.eye(6)
print("Array identidad 6x6:")
print(array_identidad)

# Creamos un array con valores aleatorios de forma 3x3x3.
array_aleatorio = np.random.rand(3, 3, 3)
print("Array aleatorio 3x3x3:")
print(array_aleatorio)

# Creamos dos arrays aleatorios A y B de la misma forma.
A = np.random.randint(0, 10, (3, 3)) #randint genera números enteros aleatorios en un rango especificado
B = np.random.randint(0, 10, (3, 3))

print("Array A:")
print(A)
print("Array B:")
print(B)

# Comprobamos si son iguales con distintas opciones:

# 1. Comparación elemento a elemento (devuelve un array de booleanos)
print("Comparación elemento a elemento:")
print(A == B)

# 2. np.array_equal -> compara forma y valores, devuelve un único booleano
print("¿Son iguales (array_equal)?:", np.array_equal(A, B))

# 3. all() sobre la comparación elemento a elemento
print("¿Son iguales (all)?:", (A == B).all())

# 4. np.allclose -> compara con tolerancia, útil para arrays de decimales
print("¿Son iguales (allclose)?:", np.allclose(A, B))


Array original:
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
Array invertido:
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]
Array 3x3:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array identidad 6x6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Array aleatorio 3x3x3:
[[[0.25795343 0

### ***Apartado 2. NumPy: conversión de valores***

**NOTA:** *En el apartado del ejercicio me pide que cree el array **dólares** (con tilde) pero usamos **dolares** sin tilde, lo cual en Python es perfectamente válido y de hecho es buena práctica evitar tildes en nombres de variables*

In [2]:
# Creamos un array de 100 valores aleatorios enteros entre 1 y 1000.
dolares = np.random.randint(1, 1001, 100)
print("Array aleatorio de 100 valores entre 1 y 1000:")
print(dolares)

# Creamos otro array llamado Euro con los mismos valores pero convertidos a euros (1 USD = 0,874413 EUR) redondeado a 2 decimales.
euros = np.round(dolares * 0.874413, 2)
print("Array convertido a euros:")
print(euros)

# Aunque prefiero mantener un codigo mas simple y limpio como el de arriba
# tambien muetro las otras dos conversiones segun se puede leer en el enunciado del ejercicio

euros_v1 = np.round(dolares * 0.874413, 2)
euros_v2 = np.round(dolares / 1.14362, 2)

print(np.allclose(euros_v1, euros_v2)) # da como resultado False, ya que no son exactamente iguales, aunque si muy parecidos.


Array aleatorio de 100 valores entre 1 y 1000:
[100 298  38 905 278  21 336 720 679 572 651 830 893 225 157 449 829 977
  79 677 376 118 870 387 605 929 258 771 133 585 185 636  20 583 230  36
 600 784 624  91 840 355 882 786 351 200 697 504  94 409  94 979 525 245
 379 504 223  48 153 155 955 391 848 600 292 461 682 420 163 802 457 690
  47 384  16 465 341 517 808 615 277 146 296 813 772 837 673  87 343 213
 918 374 858 855 436 263 788 220 673 726]
Array convertido a euros:
[ 87.44 260.58  33.23 791.34 243.09  18.36 293.8  629.58 593.73 500.16
 569.24 725.76 780.85 196.74 137.28 392.61 724.89 854.3   69.08 591.98
 328.78 103.18 760.74 338.4  529.02 812.33 225.6  674.17 116.3  511.53
 161.77 556.13  17.49 509.78 201.11  31.48 524.65 685.54 545.63  79.57
 734.51 310.42 771.23 687.29 306.92 174.88 609.47 440.7   82.19 357.63
  82.19 856.05 459.07 214.23 331.4  440.7  194.99  41.97 133.79 135.53
 835.06 341.9  741.5  524.65 255.33 403.1  596.35 367.25 142.53 701.28
 399.61 603.34  41.1  3

### ***Apartado 3. pandas y dataset tips de seaborn***

In [3]:
import pandas as pd
import seaborn as sns

# Cargamos el dataset de ejemplo "tips" de Seaborn.
df = sns.load_dataset("tips")

# Mostramos los 5 primeros registros.
print("Primeros 5 registros del dataset 'tips':\n")
print(df.head())

# Mostraamos el numero total de registros y columnas.
print("\nNúmero total de registros y columnas:")
print("Número total de registros:", len(df)) 

# Calculamos la propina media y la cuenta media.
print("\nPropina media:", df["tip"].mean()) #mean() calcula la media de los valores de la columna especificada
print("Cuenta media:", df["total_bill"].mean())

# Creamos la columna pct_tip y mostramos las 5 filas con mayor porcentaje.
df["pct_tip"] = df["tip"] / df["total_bill"] * 100
print("\n5 Filas con mayor porcentaje de propina:")
print(df.nlargest(5, "pct_tip"))

# Mostramos las 10 cuentas más altas con su propina y porcentaje.
print("\n10 Cuentas más altas con su propina y porcentaje:")
print(df.nlargest(10, "total_bill")[["total_bill", "tip", "pct_tip"]])

# Mostramos el promedio de propina por día ordenado de mayor a menor.
print("\nPromedio de propina por día (ordenado de mayor a menor):")
print(df.groupby("day")["tip"].mean().sort_values(ascending=False)) #groupby() agrupa los datos por la columna especificada, 
# mean() calcula la media de cada grupo y sort_values() ordena los valores

# Mostramos el promedio de pct_tip por sexo y por condición de fumador.
print("\nPromedio de pct_tip por sexo y por condición de fumador:")
print(df.groupby(["sex", "smoker"])["pct_tip"].mean()) #groupby() agrupa los datos por las columnas especificadas.

# Indicamos el día y momento en el que se registró la cuenta más alta.
max_bill = df["total_bill"].idxmax() # idxmax() devuelve el índice del valor máximo de la columna especificada
print("\nDía y momento de la cuenta más alta:")
print(df.loc[max_bill, ["day", "time"]]) # loc[] permite acceder a una fila o columna específica del DataFrame por su índice o nombre de columna.

# Mostramos cuántos registros corresponden a Lunch y Dinner.
print("\nNúmero de registros por tipo de comida:")
print(df["time"].value_counts()) # value_counts() cuenta el número de ocurrencias de cada valor en la columna especificada.

# Mostramos la propina media por tamaño de mesa e indicamos cuál deja mayor porcentaje.
print("\nPropina media por tamaño de mesa:")
print(df.groupby("size")["tip"].mean()) # groupby() agrupa los datos por la columna especificada y mean() calcula la media de cada grupo.
print("\nTamaño de mesa que deja mayor porcentaje de propina:")
print(df.groupby("size")["pct_tip"].mean().idxmax()) # idxmax() devuelve el índice del valor máximo de la columna especificada.

# Filtramos mesas de 5 o más personas y calcula su pct_tip medio.
print("\nPromedio de pct_tip para mesas de 5 o más personas:")
print(df[df["size"] >= 5]["pct_tip"].mean()) # filtra las filas del DataFrame donde el tamaño de la mesa es mayor o igual a 5 y calcula la media de la columna pct_tip.

# Calculamos, por día, la facturación total y el total de propinas.
print("\nFacturación total y total de propinas por día:")
facturacion_propinas = df.groupby("day")[["total_bill", "tip"]].sum() # groupby() agrupa los datos por la columna especificada y sum() calcula la suma de cada grupo.
print(facturacion_propinas)

# Calculamos la correlación entre total_bill y tip y comentamos el resultado.
correlacion = df["total_bill"].corr(df["tip"]) # corr() calcula la correlación entre dos columnas.
print("\nCorrelación entre total_bill y tip:")
print(correlacion)
# La correlación es positiva y cercana a 0.67, lo que indica que a medida que aumenta la cuenta total, también tiende a aumentar la propina.

# Exportamos a CSV las columnas indicadas en un archivo tips_resumen.csv.
df[["total_bill", "tip", "pct_tip", "sex", "smoker", "day", "time", "size"]].to_csv("tips_resumen.csv", index=False)

Primeros 5 registros del dataset 'tips':

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Número total de registros y columnas:
Número total de registros: 244

Propina media: 2.99827868852459
Cuenta media: 19.78594262295082

5 Filas con mayor porcentaje de propina:
     total_bill   tip     sex smoker  day    time  size    pct_tip
172        7.25  5.15    Male    Yes  Sun  Dinner     2  71.034483
178        9.60  4.00  Female    Yes  Sun  Dinner     2  41.666667
67         3.07  1.00  Female    Yes  Sat  Dinner     1  32.573290
232       11.61  3.39    Male     No  Sat  Dinner     2  29.198966
183       23.17  6.50    Male    Yes  Sun  Dinner     4  28.053517

10 Cuentas más altas con su propina y porcentaje:
    

### ***Apartado 4. pandas y datasets de IMDb***

*Para obtener un acabado mas profesional y legible al ojo humano, usamos `display()` de IPython para todos los resultados que sean DataFrames o Series (tablas), y dejamos `print()` solo para los textos descriptivos y los valores únicos (números, contadores).*

In [ ]:
from IPython.display import display #display() permite mostrar DataFrames de manera más legible en Jupyter Notebook.

# Cargamos los ficheros imdb_titulos.csv y imdb_elenco.csv como DataFrames.
imdb_titulos = pd.read_csv('imdb_titulos.csv', delimiter=',') # delimiter=',' indica que el separador de columnas es la coma, ya que los archivos CSV pueden tener distintos delimitadores.
imdb_elenco = pd.read_csv('imdb_elenco.csv', delimiter=',')

# Mostramos los 5 primeros registros de cada DataFrame.
print("Primeros 5 registros de imdb_titulos:")
display(imdb_titulos.head()) # head() devuelve las primeras 5 filas del DataFrame

print("\nPrimeros 5 registros de imdb_elenco:")
display(imdb_elenco.head())

# Mostramos el número total de registros y columnas de cada DataFrame.
print("\nNúmero total de registros y columnas de imdb_titulos:", imdb_titulos.shape) # shape devuelve una tupla con el número de filas y columnas del DataFrame
print("Número total de registros y columnas de imdb_elenco:", imdb_elenco.shape)

# Mostramos las 5 películas más antiguas.
print("\n5 películas más antiguas:")
display(imdb_titulos.nsmallest(5, "year")[["title", "year"]]) # nsmallest() devuelve las n filas con los valores más pequeños de la columna especificada

# Mostramos las películas cuyo título contenga la palabra "Dracula" y el total de coincidencias.
print("\nPelículas cuyo título contiene 'Dracula':")
dracula_movies = imdb_titulos[imdb_titulos["title"].str.contains("Dracula", case=False, na=False)]
display(dracula_movies[["title", "year"]])
print("Total de coincidencias:", len(dracula_movies))

# Mostramos los 10 títulos más repetidos.
print("\n10 títulos más repetidos:")
display(imdb_titulos["title"].value_counts().head(10)) # value_counts() cuenta el número de ocurrencias de cada valor en la columna especificada y head(10) devuelve las primeras 10 filas del resultado.

# Mostramos la primera película titulada "Romeo and Juliet".
print("\nPrimera película titulada 'Romeo and Juliet':")
romeo_juliet = imdb_titulos[imdb_titulos["title"] == "Romeo and Juliet"].sort_values("year").head(1)
display(romeo_juliet[["title", "year"]])

# Listamos las películas que contengan "Exorcist" ordenadas por año.
print("\nPelículas que contienen 'Exorcist' ordenadas por año:")
exorcist_movies = imdb_titulos[imdb_titulos["title"].str.contains("Exorcist", case=False, na=False)].sort_values("year")
display(exorcist_movies[["title", "year"]])

# Mostramos cuántas películas se hicieron en 1950.
movies_1950 = imdb_titulos[imdb_titulos["year"] == 1950]
print("\nNúmero de películas hechas en 1950:", len(movies_1950))

# Mostramos cuántas películas se hicieron entre 1950 y 1959.
movies_1950_1959 = imdb_titulos[(imdb_titulos["year"] >= 1950) & (imdb_titulos["year"] <= 1959)]
print("Número de películas hechas entre 1950 y 1959:", len(movies_1950_1959))

# Mostramos todos los papeles de la película "The Godfather" y el número total.
print("\nPapeles de la película 'The Godfather':")
godfather_roles = imdb_elenco[imdb_elenco["title"] == "The Godfather"]
display(godfather_roles[["name", "character"]])
print("Número total de papeles en 'The Godfather':", len(godfather_roles))

# Mostramos el elenco ordenado por clasificación n de "Dracula" (1958).
print("\nElenco de 'Dracula' (1958) ordenado por clasificación n:")
dracula_1958_cast = imdb_elenco[(imdb_elenco["title"] == "Dracula") & (imdb_elenco["year"] == 1958)].sort_values("n")
display(dracula_1958_cast[["name", "character", "n"]])

# Mostramos cuántos papeles existen de "Bruce Wayne".
bruce_wayne_roles = imdb_elenco[imdb_elenco["character"].str.contains("Bruce Wayne", case=False, na=False)]
print("\nNúmero de papeles de 'Bruce Wayne':", len(bruce_wayne_roles))

# Mostramos cuántos papeles ha interpretado "Robert De Niro".
robert_de_niro_roles = imdb_elenco[imdb_elenco["name"].str.contains("Robert De Niro", case=False, na=False)]
print("Número de papeles interpretados por 'Robert De Niro':", len(robert_de_niro_roles))

# Listamos los papeles protagonistas (n=1) de Charlton Heston en los años 60.
print("\nPapeles protagonistas (n=1) de Charlton Heston en los años 60:")
charlton_heston_roles_60s = imdb_elenco[
    (imdb_elenco["name"].str.contains("Charlton Heston", case=False, na=False)) &
    (imdb_elenco["n"] == 1) &
    (imdb_elenco["year"] >= 1960) &
    (imdb_elenco["year"] < 1970)
]
display(charlton_heston_roles_60s[["title", "year", "character"]])

# Confirmamos los tipos de valores únicos en la columna "type" del DataFrame imdb_elenco.
print("\nValores únicos en la columna 'type':", imdb_elenco["type"].unique())

# Mostramos cuántos papeles de actores hubo en los años 50.
actores_roles_50s = imdb_elenco[
    (imdb_elenco["n"] == 1) &
    (imdb_elenco["year"] >= 1950) &
    (imdb_elenco["year"] < 1960) &
    (imdb_elenco["type"] == "actor")
]
print("\nNúmero de papeles de actores en los años 50:", len(actores_roles_50s))

# Mostramos cuántos papeles de actrices hubo en los años 50.
actrices_roles_50s = imdb_elenco[
    (imdb_elenco["n"] == 1) &
    (imdb_elenco["year"] >= 1950) &
    (imdb_elenco["year"] < 1960) &
    (imdb_elenco["type"] == "actress")
]
print("Número de papeles de actrices en los años 50:", len(actrices_roles_50s))

Primeros 5 registros de imdb_titulos:


,title,year
0,Mahler,1974
1,"Ogon, voda i... mednye truby",1968
2,Ana Nojoom bent alasherah wamotalagah,2014
3,Malu de Bicicleta,2010
4,Nazareno Apostol: Boy Ahas,1989



Primeros 5 registros de imdb_elenco:


,title,year,name,type,character,n
0,Closet Monster,2015,Buffy #1,actor,Buffy 4,31.0
1,Suuri illusioni,1985,Homo $,actor,Guests,22.0
2,Battle of the Sexes,2017,$hutter,actor,Bobby Riggs Fan,10.0
3,Secret in Their Eyes,2015,$hutter,actor,2002 Dodger Fan,NaN
4,Steve Jobs,2015,$hutter,actor,1988 Opera House Patron,NaN



Número total de registros y columnas de imdb_titulos: (230407, 2)
Número total de registros y columnas de imdb_elenco: (3564650, 6)

5 películas más antiguas:


,title,year
13229,Miss Jerry,1894
103233,The Startled Lover,1898
133020,Reproduction of the Corbett and Jeffries Fight,1899
51528,Family Troubles (II),1900
111320,Trouble in Hogan's Alley,1900



Películas cuyo título contiene 'Dracula':


,title,year
3903,Bonnie & Clyde vs. Dracula,2008
4851,House of Dracula,1945
13441,Batman Dracula,1964
15371,Young-guwa heubhyeolgwi dracula,1992
20794,Terror of Dracula,2012
...,...,...
214826,Dracula's Dog,1978
221137,Dracula Now,2015
224233,The Satanic Rites of Dracula,1973
228121,Son of Dracula,1974


Total de coincidencias: 84

10 títulos más repetidos:


title
Hamlet                  19
Carmen                  16
Macbeth                 15
Othello                 11
Hero                    11
The Three Musketeers    11
Maya                    11
The Outsider            11
Kismet                  10
Paradise                10
Name: count, dtype: int64


Primera película titulada 'Romeo and Juliet':


,title,year
124702,Romeo and Juliet,1916



Películas que contienen 'Exorcist' ordenadas por año:


,title,year
88003,The Exorcist,1973
49658,O Exorcista de Mulheres,1974
118920,Satanico Pandemonium: La Sexorcista,1975
140519,Exorcist II: The Heretic,1977
220073,Kung Fu Exorcist,1978
17375,The Exorcist III,1990
132451,Teenage Exorcist,1991
117797,Exorcist: The Beginning,2004
94189,Dominion: Prequel to the Exorcist,2005
209250,Costa Chica: Confession of an Exorcist,2006



Número de películas hechas en 1950: 1081
Número de películas hechas entre 1950 y 1959: 12606

Papeles de la película 'The Godfather':


,name,character
51214,Chris Anastasio,Policeman
102809,Norm Bacchiocchi,Luca Brasi's Assassin
220852,Rudy Bond,Cuneo
248000,Marlon Brando,Don Vito Corleone
248738,Max Brandt,Extra in Furniture-Moving Scene
...,...,...
3137607,Carol Morley,Night Nurse
3360381,Ardell Sheridan,Mrs. Clemenza
3363276,Talia Shire,Connie
3390198,Filomena Spagnuolo,Extra in Wedding Scene


Número total de papeles en 'The Godfather': 76

Elenco de 'Dracula' (1958) ordenado por clasificación n:


,name,character,n
485197,Peter Cushing,Doctor Van Helsing,1.0
1242307,Christopher Lee,Dracula,2.0
1242308,Christopher Lee,Count Dracula,2.0
822398,Michael Gough,Arthur,3.0
3410427,Melissa Stribling,Mina,4.0
3069196,Carol Marsh,Lucy,5.0
2677557,Olga Dickie,Gerda,6.0
2220986,John Van Eyssen,Jonathan,7.0
2777216,Valerie Gaunt,Vampire Woman,8.0
2731182,Janina Faye,Tania,9.0



Número de papeles de 'Bruce Wayne': 49
Número de papeles interpretados por 'Robert De Niro': 103

Papeles protagonistas (n=1) de Charlton Heston en los años 60:


,title,year,character
944038,55 Days at Peking,1963,Maj. Matt Lewis
944050,Counterpoint,1967,Lionel Evans
944052,Diamond Head,1962,Richard 'King' Howland
944054,El Cid,1961,El Cid Rodrigo de Vivar
944066,Khartoum,1966,Gen. Charles 'Chinese' Gordon
944068,Major Dundee,1965,Major Amos Charles Dundee
944074,Number One,1969,Ron 'Cat' Catlan
944077,Planet of the Apes,1968,George Taylor
944085,The Agony and the Ecstasy,1965,Michelangelo
944101,The Pigeon That Took Rome,1962,Captain Paul MacDougall



Valores únicos en la columna 'type': <StringArray>
['actor', 'actress']
Length: 2, dtype: str

Número de papeles de actores en los años 50: 6565
Número de papeles de actrices en los años 50: 2942
